### ISSUE TITLE
Masking in travel and days before TPAC

### ISSUE THREAD

**Issue by astearns** [w3c/TPAC2022-Health-rules#11]
I mentioned problems with some travel rules in #10. Since that issue is about clear consequences, I am opening this separate issue about stronger, more specific guidance on masking before the event. I do not think this should be a rule with tracking or enforcement for TPAC, merely a suggestion for people to consider.

We should be doing our best to avoid transmission among our colleagues. Masking and testing during the meeting are ~good~ essential, but these safeguards will be bolstered if people agree to be more careful in the days leading up to the meeting. I think that we should be setting a higher standard for ourselves than any current state or company guidelines.

I would like to see something like this adopted as a strong suggestion for TPAC:

Use masks consistently in public places for several days before TPAC begins. This is particularly important for travel. Airplanes have relatively good ventilation, but keep a mask on in the airplane. You should lower your mask only to take sips of water or bites of food in the airplane. In all other public travel places (airports, taxis, trains, etc.) you should try to keep your mask on at all times, lowering it only to take sips of water. If you must eat, take steps to isolate from others, choose the most well-ventilated space, and only lower your mask for each bite.

**Comment by FremyCompany** [comment]
This looks absolutely reasonable.

**Comment by FremyCompany** [comment]
I saw in the other thread a mention of "when taking medication" which makes sense as an additional exception.

**Comment by megangardner** [comment]
I strongly agree with this rule, but we should specify exactly what "several days" means. 72 hours before a flight? 3 days before the beginning of TPAC? 5 days before the start of travel? 48 hours before the beginning of TPAC? Several is too up to interpretation.

I propose "72 hours before the first meeting of TPAC that you will attend."

While I have heard of people developing symptoms more than 3 days after exposure, 3 days is my understanding of the common incubation time. If someone catches it before the period of increased caution, in theory they should manifest symptoms/test positive before meeting with others in person. This would be unfortunate if you travel far and then must isolate instead of participating in person, but that's a risk each person can decide to take.
And I did just say 3 day several times, but I'm proposing 72 hours before meeting time because that is a very exact number that is not subject to what a "day" is. 
If people think it should be longer, I am amenable, but I think this is the minimum amount of time for increased caution.

**Comment by emilio** [comment]
I assume public places really means public _indoor_ places? But yeah if so that seems reasonable.

**Comment by svgeesus** [comment]
This looks much better worded (agree with the need to clarify "few days") and I hope there is still time to get it adopted TPAC-wide.

**Comment by astearns** [comment]
@alexandralacourba @plehegar what do you think?

**Comment by cwilso** [comment]
I'm definitely in favor of being prescriptive.  I do think it is VERY important to be more reasonable in terms of travel rules (Alan's proposal above is strict but reasonable; (the current restrictions say "Wear a mask during your entire travel journey (onboard a flight, train or federally-regulated vessel, as well as in airports and other points of entry)", but don't say it is permissible to eat/drink).

That said: the typical incubation period for COVID from exposure to positive test is closer to a week; I'm not sure asking attendees to wear masks for a week leading up to TPAC is realistic.  I think we need to focus on close adherence to protocols in-event to prevent any spread.  (By the time you test positive, you have probably been shedding and contagious for at least a couple of days.)

**Comment by alexandralacourba** [comment]
We already reminded people to wear a mask while traveling: https://lists.w3.org/Archives/Member/w3c-ac-members/2022JulSep/0029.html. Eating/drinking are currently allowed at airports and in planes.

We can also recommend people to wear a mask in public indoor places.
72 hours before the first meeting of TPAC that people will attend seems reasonable and adequate as the incubation period of the current variant is around 2 days.  (several recent examples show this patterns)

**Comment by alexandralacourba** [comment]
We sent an email this week with the following recommendations: 
--------------------------------------------------------------------------------
Recommendation before coming to TPAC and during the event
--------------------------------------------------------------------------------

We also strongly advise you to wear a mask that covers your nose and mouth:

- in all indoor public space 72 hours before the first meeting of TPAC that you will attend, and during your stay in Vancouver
- while traveling to TPAC

You should lower your mask only to take sips of water or bites of food in the airplane.

For meals in public place, try to isolate from others or limit the number of guests at one table, choose the most well-ventilated space, or outside space.

-----
We also add these to the health rules

**Comment by plehegar** [comment]
Seems to me that this issue can be closed since everything that can be done was done.
