### ISSUE TITLE
Problematic reformulation of Canada's federal rules

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#12]
(This partly, but only partly, overlaps with #10 and #11)

Problem
----

The TPAC rules state:

> While traveling and after your arrival
> 
>  There are some federal requirements that you must follow for 14 days after entry into Canada. You are required to:
> 
> * Report any positive results from a government-required test if you were selected to complete one
> * Wear a mask during your entire travel journey (onboard a flight, train or federally-regulated vessel, as well as in airports and other points of entry)

There are three problems with that:
* The TPAC rules do not merely point to the official rules, they also say "you are required to: […]", which is a little ambiguous: while it might just be a reminder of the Canadian rules, it might also be a statement that TPAC itself insists that you follow these rules. The important difference could be that if you do not follow the rules as stated, in addition to whatever problem you might get into with Canada, this would also be violation of TPAC rules, possibly leading to TPAC specific consequences.
* The TPAC specific consequences are not listed. Arguably, if you do not follow the rules of an event, you will be denied access to the event. But it is not stated, so it is not clear. (see #10)
* This restatement of the Canadian rules is not actually identical to the original rules. And in particular, what is stated about masks here is stricter than the official rules, and arguably impossible to apply. The official rules say that you must wear a masks during the entire journey **except for brief periods while eating, drinking, or taking oral medication, or unless otherwise exempt**. This restatement does not include the exception. Requiring no food or drink (or medication) for the entire travel, with no exception, isn't practical.

Suggestion
----

Separate the “Health rules” section into two:
* TPAC Health rules
     List there things that TPAC itself demands. Include description of consequences for non-respect of the rules (see #10)
* Other Health information
    List there things that are good to know, laws and regulations people need to follow (separately of what TPAC itself requires), and general guidance that we think is wise to follow, but do not outright require. I suspect that expected behavior during travel before TPAC should be there (see #11), rather than in the TPAC rules section.

**Comment by alexandralacourba** [comment]
The health rules document has different part: the trip and onsite rules. We keep this.
For the trip part, we need to rely on the rules from the Canadian Government as we can not impose rules that must be followed outside of our event. We can strongly recommend things or rely on the Canadian Government rules. In this case, they require masks while traveling so this what we will state. There was no precision about food and drinks when we set up the rules. I will then add "except for brief periods while eating, drinking, or taking oral medication, or unless otherwise exempt".

**Comment by frivoal** [comment]
> I will then add "except for brief periods while eating, drinking, or taking oral medication, or unless otherwise exempt".

Thanks.

> we need to rely on the rules from the Canadian Government as **we can not impose** rules that must be followed outside of our event.

Thanks for the clarification. Yet the wording says "you are required to", which may suggest that we are trying to impose such things ourselves, in addition to the Canadian government, and that there might be (unstated) penalties applied by W3C if this is not followed. As this is not what you intend, I suggest rephrasing to:

> There are some federal requirements that you must follow for 14 days after entry into Canada. <del>You are required to<del><ins>They include</ins>:

**Comment by alexandralacourba** [comment]
Good point. I removed "you are required to"
