### ISSUE TITLE
Contradiction about testing in rules

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#13]
The [on-site W3C rules](https://www.w3.org/2022/09/TPAC/health.html#on-site) for TPAC state two things which seem contradictory to me:
* near the beginning:
    > We are not planning to require COVID-19 tests for all attendees at this stage
* In the Iconified bullet list:
    > We intend to provide COVID rapid antigen test kits each day to meeting attendees.
    > Each attendee will agree to take a COVID rapid antigen test each day before attending an in-person event if W3C provides test kits

Are we requiring daily tests or not?

**Comment by frivoal** [comment]
Also note that further down, it does state:
> COVID rapid antigen tests will be distributed to meeting attendees.

So at one point in the rules, we say that we "intend" to provide tests, which sounds like this may happen, but isn't certain. And a few lines further down we state that we "will", making it a certainty.

Please elliminate these ambiguities. I suggest doing so by:
* removing the "we are not planning[…]" sentence
* rephrase: We <del>intend to</del><ins>will</ins> provide COVID rapid antigen test kits
* rephrase: Each attendee will agree to take a COVID rapid antigen test each day before attending an in-person event<del> if W3C provides test kits</del>

**Comment by alexandralacourba** [comment]
Something went clearly wrong here as this sentence "We are not planning to require COVID-19 tests for all attendees at this stage" should be removed for weeks. 
I also made the modifications based on your second comment
