### ISSUE TITLE
Remove unecessary piece of commentary

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#14]
The TPAC health rules are very long, and should be shortened for better readability and ease of understanding.

Point 3 of the itemized list in the "Entry requirements" section states:
> According to the British Columbia Province: ‘Individual businesses and event organizers can choose to continue requiring masks on their premises. It's important that we respect the choices of people, businesses and one another.’
> 
> **TPAC attendees must wear a mask at all times in all common spaces and meeting rooms, except when consuming food or beverages.** 

The first paragraph is entirely unnecessary, and should be deleted.

**Comment by alexandralacourba** [comment]
Removed
