### ISSUE TITLE
Consolidate rules about masks, food, and beverages

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#15]
The [TPAC health rules page](https://www.w3.org/2022/09/TPAC/health.html) speaks about masking rules and related food and drinks exception in several spots, while saying things that are complimentary but different:

* Most of the information about masking requirements are in the 3rd entry of the itemized list in the “Entry requirements” section. Here, the exception to the requirement to wear masks is phrased as “except when consuming food or beverages.”
* The “Event safety measure“ also says that “Food will be forbidden into the meeting rooms and will be consumed in the breaks and meals dedicated space. You may only remove your mask while drinking, and must put your mask back on immediately afterwards. Masks must be absolutely worn while speaking.”

If you combine the two, I believe this means that:
* in meeting rooms, participants must not eat, and therefore cannot remove their masks to do so, but that they may remove their masks to take a sip of their drink. However, in rooms other than meeting rooms, participants may remove their masks to eat or drink.
* the “Masks must be absolutely worn while speaking” requirement to applies both in and out of meeting rooms, though this looks slightly ambiguous.

It should not be necessary to read multiple pieces of text and to think about their interaction to know what the rules are. I recommend consolidating everything into the 3rd entry of the itemized list in the “Entry requirements” section.

**Comment by alexandralacourba** [comment]
It think it is clearer to leave food and drinks details under "the event safety measures" instead of the "entry requirements" section.
But I added : See the "event safety measures section below for more details about food and beverages consumption". after "TPAC attendees must wear a mask at all times in all common spaces and meeting rooms, except when consuming food or beverages. "

**Comment by frivoal** [comment]
> But I added : See the "event safety measures section below[…]

Thanks, that works for me. Maybe also add an id to the event safety measures, and turn that reference into a hyperlink?

**Comment by alexandralacourba** [comment]
Yes, this will be added.
