### ISSUE TITLE
Remove unnecessary text about contact tracing

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#17]
The [TPAC health rules](https://www.w3.org/2022/09/TPAC/health.html) page is very long, and should be trimmed down to make it easier to read. As it is, it is very likely to be skimmed rather than read by many participants, which will likely result in less than perfect levels of compliance.

The 5th entry in the itemized list of the Entry requirements section says
> Positive tests and contact tracing: If you test positive, contact the public health authority (contact will be added soon) and follow their instructions.

That is reasonable and useful, assuming that Canada still does contact tracing, which I am far from sure. For instance, the British Columbia health authorities don't seem to indicate an active contact tracing program http://www.bccdc.ca/health-info/diseases-conditions/covid-19/self-isolation/close-contacts.

> Please also stay in touch with the [TPAC Event organizers](https://www.w3.org/2022/09/TPAC/Overview.html#helpdesk).

That too is reasonable (although it would be better to be clear if this is something that is required, or merely suggested).

However, between these two sentences, it has a lengthy description of what contact tracing is, why it's useful, and what public health officials might ask you about. This not a rule to be followed, merely informative text. This is unnecessary, and makes the rules page needlessly long. This should be deleted. At this point in the pandemic, most people know about contact tracing. And even if they don't, the goal of this page is not to educate people about COVID and related procedure, but to lay out the information and rules that relate to our event.

**Comment by alexandralacourba** [comment]
I removed: 
[A public health official will ask you questions to collect important information about:

    your symptoms
    activities and travel you did before you tested positive
    all the people you may have been in close contact with while you were contagious

This is called contact tracing. It's a key public health measure to slow down or stop the spread of the virus.]
