### ISSUE TITLE
Venue for Welcome reception and Technical plenary reception

### ISSUE THREAD

**Issue by frivoal** [w3c/TPAC2022-Health-rules#19]
The [TPAC health rules page](https://www.w3.org/2022/09/TPAC/health.html) states that lunch will be offered in the form of lunch box, which can be taken anywhere the participant wants, enabling people to eat outside.

The schedule also includes:
* a Welcome reception on Monday, from 18:00 to 19:00
* a Technical plenary reception on Wednesday from 18:30​–21:00

I presume that food and drinks might be served at these events. If so, what is the venue for these events? As previously discussed (see [AB minutes](https://www.w3.org/2022/06/16-ab-minutes.html#t06)  for instance), I expect that food and drinks should primarily or (if possible) exclusively be served outdoors. Is that the case here?

**Comment by alexandralacourba** [comment]
All the meals will take place a the same place including the welcome reception and TP reception. As already mentioned, we will have an outside space as well as in indoor space. The food will be served inside for logistics and weather conditions reasons and people will be able to take it outside. 
For the welcome reception, we'll have light food and drinks which will be served by servers. For the TP reception, we are also planning a take away solution similar to lunches but a bit more convivial than lunchboxes.

**Comment by frivoal** [comment]
> For the welcome reception, we'll have light food and drinks which will be served by servers.

So, if I understand correctly, food&drinks will be served indoors, and can be consumed in the place where they are served, or taken outdoors, at the choice of the attendee. Is that right?

**Comment by alexandralacourba** [comment]
Right

**Comment by frivoal** [comment]
Maybe I am picturing the venue wrong, since I have not seen it, but if I understand correctly, that means that it will not be possible for people who want to attend the reception outside to avoid going through an indoor space where people are having food and drinks unmasked. That seems unfortunate.

**Comment by alexandralacourba** [comment]
Hold on that aspect. We are double checking if it is possible to get a food station outside. Will let you know

**Comment by alexandralacourba** [comment]
The breaks (food and drinks) will be available both in the inside and outdoor spaces.
For lunches, the food and beverage station will be located outside. We will only have a beverage station outside. 
The food and beverage station inside will be separated from the tables. People taking their food will not in direct contact with people eating.
We'll send a communication today: the welcome reception on Monday will be cancelled. Given the number of registered people and the short duration of this event (one hour) we cannot guarantee the security of the attendees.
The reception on Wednesday is maintained as will be able to regulate the flow if we have too many people in one place.
Same as for the lunches, we will have the food station inside for the Wednesday reception, and people will be able to take their food outside. Only drinks will be available outside (and inside of course) Note that we will not be able to serve alcohol during this reception as it is not permitted outside (even holding a glass, not only the fact to serve alcohol).

**Comment by frivoal** [comment]
Thank you for the clarifications, and the extra steps taken given the high attendance. Appreciated.
