### ISSUE TITLE
Hugs and handshakes

### ISSUE THREAD

**Issue by dwsinger** [w3c/TPAC2022-Health-rules#2]
I doubt we need to set, or could or would, enforce a rule that applies to consensual behavior between two people (CEPC rules continue to apply, of course)

**Comment by swickr** [comment]
I understand that some participants wish to have indicators of their preferences that are identifiable without having to ask.  This avoids some social mis-steps, e.g. offering a handshake that is declined.

**Comment by LJWatson** [comment]
I agree with @dwsinger that any rule would be difficult to enforce. I like @swickr's suggestion, but note the inherent inaccessibility of indicators for those of us who can't see them.

Perhaps something as simple as some guidance on how people can approach the question in social situations? For example, I've just taken to asking people "are you hugging"?"

**Comment by dwsinger** [comment]
@LJWatson Yes, I offer an elbow or a hand and allow the other to offer something else. honestly anything like a hug is already strongly consensual (for CEPC reasons), and I don't think the virus makes any difference to the hug-answer, which is only if you have explicit mutual consensus anyway.

**Comment by alexandralacourba** [comment]
The hugs and handshakes mention has been removed. 
We now stated" All attendees shall respect the personal boundaries of all fellow participants"
and "Attendees will be able to indicate social distancing rules preference they expect from others".
We are planning to have ribbons (to stick them under the badge) available to indicate the level of social distancing an attendee is expecting.

**Comment by frivoal** [comment]
I believe this has been addressed to satisfaction. Can this issue be closed?

**Comment by alexandralacourba** [comment]
Fine by me to close the issue.
