### ISSUE TITLE
Should proof of vaccination be required for in-person TPAC attendees?

### ISSUE THREAD

**Issue by swickr** [w3c/TPAC2022-Health-rules#3]
The question was raised in the 10/11-May AC Office Hours sessions whether in-person TPAC attendees should be required to show proof of vaccination or not.  Since the goal of TPAC is to reduce as many barriers to broad participation as possible, would a vaccine mandate allow some who are concerned for their own health be more likely to attend or would such a mandate deter some from attending?

**Comment by frivoal** [comment]
If Canada requires vaccines to get to the venue (I think it does), maybe we get this one without having to do anything? Otherwise, @dwsinger mentioned some venues requiring use of a third party app that handles the collection and verification of (international) vaccine certificates.

**Comment by dwsinger** [comment]
The Emmy awards used the Clear App;  I uploaded photos of myself, my ID, and my vaccination cert., which they verified and gave me a pass I could display on my phone (no cost to attendees).

**Comment by swickr** [comment]
Like @dwsinger's experience, the Boston Marathon used CrowdPass for all volunteers.   David's description of the process matches mine, though I didn't have to upload a photo.  Possibly because the BAA had already completed its separate registration of all the volunteers.  We techies noticed some possible security flaws in the process but decided not to make issues of them.

**Comment by samuelweiler** [comment]
I'm very concerned about safety (IMHO), and I don't need a vaccine mandate at this time.  That was different last summer, when the vaccines seemed to be having a larger "keep you from getting sick at all" effect, and it might be different if we again have a (variant-specific) vaccine with high neutralizing effect.  But even if we get such a vaccine this fall, we're unlikely to have it in sufficient quantity by September to require it.

If we are requiring proof of vaccine, I'm less a fan of the apps - I would prefer the option to simply show my proof in person, without having it retained by an org with a non-negotiable privacy policy.

**Comment by frivoal** [comment]
> I'm less a fan of the apps - I would prefer the option to simply show my proof in person, without having it retained by an org with a non-negotiable privacy policy.

That's understandable, but that implies that the W3C staffer who will be reviewing those needs to be capable of reviewing the validity of vaccine certificates in arbitrary languages, from an arbitrarily large number countries. I don't know how hard it is to do that.

**Comment by LJWatson** [comment]
If we want people to have the best chance of participating in confidence, especially older members of our community and/or those with underlying health conditions, then yes, we should require proof of vaccination.

As @frivoal notes though, if Canada requires proof of vaccination in order to enter the country, then is that sufficient for our purposes? If yes, then the gap is those people travelling from within Canada.

**Comment by samuelweiler** [comment]
> If we want people to have the best chance of participating in confidence, especially older members of our community and/or those with underlying health conditions, then yes, we should require proof of vaccination.

As I said in the AC meeting, I'm a fan of setting precautions closer to the event (although at least a few weeks out, so people know what to expect).  Right now, though, I would get significant confidence from a(n expected-to-be-enforced) mask requirement and very little confidence from a vaccine requirement.

> As @frivoal notes though, if Canada requires proof of vaccination in order to enter the country, then is that sufficient for our purposes? If yes, then the gap is those people travelling from within Canada.

Governments have a nasty habit of changing requirements - including dropping requirements - on very short notice.  We might want to consider contingencies for government rules changing out from under us.  e.g. if we require vaccines, maybe announce: "we require vaccines, but we're unlikely to check for proof so long as CBSA is doing it for us."  And we should consider how we might handle odd edge cases, like if CBSA stops checking on Monday, 12 September: so they'll have checked some people as they entered Canada on Saturday and Sunday but not those arriving Tuesday.

**Comment by LJWatson** [comment]
>As I said in the AC meeting, I'm a fan of setting precautions closer to the event (although at least a few weeks out, so people know what to expect). Right
now, though, I would get significant confidence from a(n expected-to-be-enforced) mask requirement and very little confidence from a vaccine requirement.

For anyone needing to book flights now before the costs become intolerable, "nearer the time" doesn't help very much unfortunately.


>Governments have a nasty habit of changing requirements - including dropping requirements - on very short notice. We might want to consider contingencies
for government rules changing out from under us. e.g. if we require vaccines, maybe announce: "we require vaccines, but we're unlikely to check for proof
so long as CBSA is doing it for us." And we should consider how we might handle odd edge cases, like if CBSA stops checking on Monday, 12 September: so
they'll have checked some people as they entered Canada on Saturday and Sunday but not those arriving Tuesday.


Good point, and good suggestion.

**Comment by fantasai** [comment]
As I wrote in https://github.com/w3c/AB-memberonly/issues/137
> Require each attendee to have all eligible vaccinations according to their home country, and include a checkbox attestation to that effect in the TPAC registration form.
> 
>    ( ) I have completed the full dose regimen of a COVID-19 vaccine.
>    ( ) I have not completed the full dose regimen of a COVID-19 vaccine because I am not eligible. (Non-eligibility includes age restrictions and medical contraindications only.)

I don't think we need to validate people's vaccination cards. If this were a restaurant or nightclub, sure. But for an intra-organization professional event, I don't think it's quite so necessary to be on the alert for liars.

**Comment by alexandralacourba** [comment]
Attendees will be asked to show a proof a vaccination in person. This is the current plan.

**Comment by fantasai** [comment]
@alexandralacourba That's fine, but I think to prevent any surprises or confusion, it would be best if the registration form asks the question I posted above nonetheless.

**Comment by alexandralacourba** [comment]
@fantasai Yes, we will do this. Thank you for the suggestion

**Comment by frivoal** [comment]
I think this has been addressed, and can be closed.
