### ISSUE TITLE
Tweak to wording of drinking rules

### ISSUE THREAD

**Issue by fantasai** [w3c/TPAC2022-Health-rules#7]
> Drinking will be tolerated inside the meetings rooms but masks should be put back on as soon as beverages are consumed

Suggest editing to

> Drinking will be tolerated inside the meetings rooms but masks should be put back on as soon as beverages are consumed and must especially be put back on before talking.

to emphasize that masks need to be worn while chatting.

**Comment by alexandralacourba** [comment]
modifications have already been made based on a suggestion made on a separate thread: "Food will be forbidden into the meeting rooms and will be consumed in the breaks and meals dedicated space. You may only remove your mask while drinking, and must put your mask back on immediately afterwards. Masks must be absolutely worn while speaking. "

**Comment by frivoal** [comment]
I believe this has been handled. Can we close this issue?

**Comment by alexandralacourba** [comment]
We can close the issue as far as I'm concerned

**Comment by frivoal** [comment]
I am not the person who opened the issue nor the repository owner, so I cannot close it myself.

**Comment by fantasai** [comment]
Closing out! I agree it's been addressed.
