### ISSUE TITLE
Masking vs disabilities

### ISSUE THREAD

**Issue by fantasai** [w3c/TPAC2022-Health-rules#8]
I suspect we need to add some wording here:

> **TPAC attendees must wear a mask at all times in all common spaces and meeting rooms, except when consuming food or beverages**

e.g.

> **TPAC attendees must wear a mask at all times in all common spaces and meeting rooms, except when consuming food or beverages** or as required to accommodate a disability.

Might want to check in with the a11y folks about it.

**Comment by plehegar** [comment]
As mentioned during the [Chair training session](https://www.w3.org/2022/Talks/TPAC/hybrid-training/#safety), there will no exception granted to avoid wearing a mask during TPAC, including for medical reasons. And if food or beverage, it needs to keep it short.
So the text has to be revised to make this clearer.

**Comment by alexandralacourba** [comment]
Note that we did not received any requests asking for exception. But there will be indeed no exception. All onsite TPAC attendees must wear a mask, as stated in the health rules.

**Comment by fantasai** [comment]
Closing this out, since it's no longer relevant.
