### ISSUE TITLE
Pre-entry testing no longer required for fully vaccinated travelers to Canada

### ISSUE THREAD

**Issue by acomminos** [w3c/TPAC2022-Health-rules#9]
[As per travel.gc.ca](https://travel.gc.ca/travel-covid/travel-restrictions/flying-canada-checklist/covid-19-testing-travellers-coming-into-canada#pre-entry-testing), pre-entry testing is no longer required for travelers qualifying as fully vaccinated.

> Travellers who don’t qualify as fully vaccinated must provide proof of a valid pre-entry test result when entering Canada by air, land or water. You must input information about your pre-entry test result in ArriveCAN.

The "Traveling to Canada" section of README.md should likely be updated to reflect this change, as it currently notes the following:

> Pre-entry testing: Negative: provide proof of a negative result taken within 72 hours of scheduled flight or land entry

**Comment by alexandralacourba** [comment]
This statement already appears on our health rules: "Pre-entry tests are not required for fully vaccinated travelers entering Canada by land, air or water."

**Comment by plehegar** [comment]
closing this since I believe our [health rules](https://www.w3.org/2022/09/TPAC/health.html) are up-to-date. Feel free to re-open is needed.
